### ISSUE TITLE
Don't default to omit

### ISSUE THREAD

**Issue by greg-hellings** [oasis-roles/nmcli_add_addrs#2]
Investigate changing defaults from `{{ omit }}` to undefined and updating conditional clauses to check for `is defined` instead of `== omit`.

**Comment by tehsmyers** [comment]
https://github.com/oasis-roles/nmcli_add_addrs/pull/1#discussion_r208793631 for reference.

It also sorta crystallizes for me what should go into the style guide. Seems like optional vars that are used for role logic should prefer the `is defined` check, and `omit` should be used when the var value gets passed through to a module.

**Comment by greg-hellings** [comment]
I'd be happy to see a style guide update covering this. It's something that's just become a reflex for me and I probably couldn't write a guide as clearly as you could if it's just crystallized for you.
